### ISSUE TITLE
jar without main manifest attribute

### ISSUE THREAD

**Issue by kiufta** [clarisma/geodesk#70]
gol-tool builds `gol-tool-0.1.1.zip` inside the target folder, where I may extract a working 13,5MB JAR from. The 12,8 MB big JAR files don't have the main manifest attribute.

geodesk however is built to *SNAPSHOT.jar files, which all fail with:
`no main manifest attribute, in ./geodesk/target/geodesk.jar`

**Comment by clarisma** [comment]
Thanks for opening this issue!

Are you trying to invoke the GOL Tool directly with a call to `java` or by double-clicking the jar?

There's a shell script in the `bin` folder (as well as a Windows `.bat` file) that launches the tool (specifying the main class explicitly).

**Comment by kiufta** [comment]
I'm doing `java -jar $file`

**Comment by clarisma** [comment]
The GOL tool is designed to be launched via the `gol` shell script in the `bin` folder of the distribution (There are versions for both Windows and *nix).

But you have a good point: There should be a manifest entry in the jar. It is now included in Version 0.1.2 (just released), so you can launch the tool using `java -jar` as well.
