### ISSUE TITLE
Windows 10: ClassNotFoundException in path with space

### ISSUE THREAD

**Issue by Discostu36** [clarisma/geodesk#77]
When I try to run geodesk on Windows 10 inside a folder with a space in its name, a ClassNotFoudException is thrown.

So for example:
```
cd "c:\Eigene Dateien\Michael\gol-tool-0.1.1\bin"
gol build germany germany-lastest.osm.pbf
```
Doesn't work because of the space in the path.

**Comment by clarisma** [comment]
Thanks for reporting this!
I fixed the `gol.bat` launcher script, it will now work properly if there are spaces in the gol-tool path. 
(You can replace `bin\gol.bat` with the [new version](https://raw.githubusercontent.com/clarisma/gol-tool/main/bin/gol.bat).)
